name: stoessel-crm

services:
  postgres:
    image: postgres:15-alpine
    container_name: stoessel_crm_db
    environment:
      POSTGRES_DB: stoessel_propiedades
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./src/sql/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    networks:
      - stoessel_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  stoessel_network:
    driver: bridge
